services:
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rust_app:
    container_name: rustapp
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - RUST_LOG=backend=debug,tower_http=debug
    ports:
      - 8080:8080
    depends_on:
      - db

  next_app:
    container_name: nextapp
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://0.0.0.0:8080
    ports:
      - 3000:3000
    depends_on:
      - rust_app

volumes:
  pgdata: {}